name: template-python
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - plotnine
  - jupyter
  - ipykernel
  - cmake
  - make
  - compilers
  - pip:
      - arviz
      - blackjax
      - cmdstanpy
      - bridgestan
      - "jax[cpu]"
