name: template-python
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipykernel
  - cmake
  - make
  - plotly
  - compilers        # conda-forge meta-package: provides gcc/g++ on linux
  - pip:
      - arviz
      - blackjax
      - cmdstanpy
      - bridgestan
      - "jax[cpu]"    # CPU build; for GPU/TPU this differs
